<?xml version="1.0" encoding="utf-8"?><Database Name="DbBlog" Class="MyDBObjectsLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ОЛЕГ-ПК\SQLEXPRESS;Initial Catalog=DbBlog;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DbBlogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Categories">
      <Column Name="Id_Category" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Categories_Record" Member="Record" ThisKey="Id_Category" OtherKey="Category_Id" Type="Record" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comment">
    <Type Name="Comment">
      <Column Name="Id_Comment" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NameAuthorComment" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="IdRecord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Record_Comment" Member="Record" ThisKey="IdRecord" OtherKey="Id_Record" Type="Record" IsForeignKey="true" />
      <Association Name="UserProfile_Comment" Member="UserProfile" ThisKey="IdUser" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MailResults" Member="MailResults">
    <Type Name="MailResults">
      <Column Name="Id_mailRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameSender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMailSender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TextSender" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThemeMail" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="TimeSending" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Record" Member="Record">
    <Type Name="Record">
      <Column Name="Id_Record" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PreviewText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateEdit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NameImageRecord" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NameVideoRecord" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Record_Comment" Member="Comment" ThisKey="Id_Record" OtherKey="IdRecord" Type="Comment" />
      <Association Name="Categories_Record" Member="Categories" ThisKey="Category_Id" OtherKey="Id_Category" Type="Categories" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfile">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_Comment" Member="Comment" ThisKey="UserId" OtherKey="IdUser" Type="Comment" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Membership">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Roles" Member="webpages_Roles">
    <Type Name="webpages_Roles">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_UsersInRoles" Member="webpages_UsersInRoles">
    <Type Name="webpages_UsersInRoles">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>